# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=512, null=True)),
                ('a', models.CharField(blank=True, max_length=255, null=True)),
                ('b', models.CharField(blank=True, max_length=255, null=True)),
                ('c', models.CharField(blank=True, max_length=255, null=True)),
                ('d', models.CharField(blank=True, max_length=255, null=True)),
                ('ans', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Category')),
            ],
            options={
                'verbose_name_plural': 'Quiz',
            },
        ),
    ]
