# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_examresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=512, null=True)),
                ('question', models.CharField(blank=True, max_length=512, null=True)),
                ('a', models.CharField(blank=True, max_length=255, null=True)),
                ('b', models.CharField(blank=True, max_length=255, null=True)),
                ('c', models.CharField(blank=True, max_length=255, null=True)),
                ('d', models.CharField(blank=True, max_length=255, null=True)),
                ('ans', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Exam',
            },
        ),
    ]
