# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
