# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_examresult_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='score',
            new_name='scores',
        ),
    ]
