# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190130_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
