# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20190201_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='tittle',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
