# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181203_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='audience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
