# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-30 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
