# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20180330_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classes',
        ),
        migrations.RenameField(
            model_name='post4',
            old_name='subject',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post4',
            old_name='subtitle',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='friend',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
