# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20181004_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='theory',
        ),
        migrations.AddField(
            model_name='post',
            name='exam',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='practicle',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='results',
            field=models.CharField(default='', max_length=120),
        ),
    ]
