# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20181005_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default=None, max_length=70, null=True, unique=True)),
                ('phone_number', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
